### ISSUE TITLE
Field `sii_xml_request` does not exist

### ISSUE THREAD

**Issue by kkoci** [dansanti/l10n_cl_dte#1]
Hola Daniel, buenas noches

Tanto en ésta versión como en la versión de odoo-chile me aparece éste error al intentar instalar el módulo (últimos commits):

`

Odoo Server Error

Traceback (most recent call last):
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 683, in dispatch
    result = self._call_function(*_self.params)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 312, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 962, in __call__
    return self.method(_args, *_kw)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 512, in response_wrap
    response = f(_args, *_kw)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/addons/base/ir/ir_ui_view.py", line 353, in create
    context=context)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/models.py", line 4157, in create
    record = self.browse(self._create(old_vals))
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/models.py", line 4354, in _create
    recs._validate_fields(vals)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Field `sii_xml_request` does not exist

Error context:
View `account.invoice.sii.form`
[view_id: 1279, xml_id: n/a, model: account.invoice, parent_id: 403]
None" while parsing /home/kristian/odoov9/solti/l10n_cl_dte/views/invoice_view.xml:4, near
<record id="view_invoice_form" model="ir.ui.view">
            <field name="model">account.invoice</field>
            <field name="name">account.invoice.sii.form</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="arch" type="xml">
              <data><header position="inside">
                <button string="Imprimir Cedible" type="object" name="print_cedible"/>
              </header>
                
                
                <field name="invoice_line_ids" position="attributes">
                    <attribute name="context">{'partner_id': partner_id, 'price_type': context.get('price_type') or False, 'type': type}" name="invoice_line_ids" on_change="onchange_invoice_line(invoice_line_ids)</attribute>
                </field>
                <notebook>
                    <page string="Electronic Invoice" name="electronic_invoice">
                        <header>
                            <button string="Download XML" type="object" name="get_xml_file" attrs="{'invisible':[('state', 'in', ['draft'])]}"/>
                            <button string="Send XML" type="object" class="oe_highlight" name="do_dte_send_invoice" attrs="{'invisible': ['|', ('state', 'in', ['draft']),('sii_send_ident', '!=', False)]}"/>
                            <button string="Ask for DTE" type="object" class="oe_highlight" name="ask_for_dte_status" attrs="{'readonly':[('sii_result','in',['','NoEnviado','Proceso'])],'invisible':[('state', 'in', ['draft']),('sii_result','in',['','NoEnviado'])]}"/>
                            <field name="sii_result" widget="statusbar"/>
                        </header>
                        <group>
                            <field name="sii_batch_number" readonly="1"/>
                            <field name="sii_barcode_img" widget="image" attrs="{'invisible':[('sii_result', '=', '')]}" readonly="1"/>
                            <field name="sii_message" attrs="{'invisible':[('sii_result', 'in', ['','NoEnviado'])]}" readonly="1"/>
                            <field name="sii_send_ident" attrs="{'invisible':[('sii_result', 'in', ['','NoEnviado'])]}" readonly="1"/>
                            <field name="sii_xml_response" attrs="{'invisible':[('sii_result', 'in', ['','NoEnviado'])]}" readonly="1"/>
                            <field name="sii_xml_request" attrs="{'invisible':[('sii_result', '=', '')]}" readonly="1"/>
                        </group>
                    </page>
                </notebook>
            </data></field>
        </record>

`
¿Alguna idea?

Ésto me ocurrió también con el "general" por decirlo así, no lo abrí (el issue) allá porque quería probar primero éste, pero me sale exactamente lo mismo :(.

**Comment by dansanti** [comment]
Hola! recuerdo haber leido de que has dejado la carpeta de lo anterio , eso puede ser una mala idea, siempre y cuando desinstales el anterior.

Si  has actualizado la carpeta. 1 debes reiniciar el servicio de odoo, 2, presionar en upgrade en el módulo , para que los xml y las tablas de la db se creen.

**Comment by kkoci** [comment]
Hola, nono, éso fué con el invoice, ésta vez desinstalé, paré el servidor, sustituí la carpeta, reinicié el servidor, y luego actualizar lista de aplicaciones (por si acaso), entonces lo instalé (todo ésto en una base de datos nueva)

De todas formas, ¿no lo puedes reproducir?

Voy a revisar mejor por si acaso, no vaya a ser que algo se me pasó

**Comment by kkoci** [comment]
Volví a revisar, creo que era otra carpeta renombrada, creo, en fin, ahora reinicio el server y dá error 500, ahora si creo que debe ser el módulo:

`2016-09-13 13:42:27,139 10519 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/kristian/.virtualenvs/odoov9/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/kristian/.virtualenvs/odoov9/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 1492, in __call__
    self.load_addons()
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/http.py", line 1513, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/kristian/odoov9/odoo-9.0c-20160712/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/kristian/odoov9/solti/l10n_cl_dte/__init__.py", line 2, in <module>
    from . import models, controllers, wizard
  File "/home/kristian/odoov9/solti/l10n_cl_dte/models/__init__.py", line 2, in <module>
    from . import invoice, partner, company, payment_term, sii_regional_offices
File "/home/kristian/odoov9/solti/l10n_cl_dte/models/invoice.py", line 500
    _logger.info(_("Token is: {}").format(token))
          ^
SyntaxError: invalid syntax
`

De todas formas éste lo descargupe ayer en la tarde, vi que actualizaste algo hace 7 horas, voy a sustituir con ése a ver qué tal

**Comment by Danisan** [comment]
@kkoci te aviso, que el campo ese, en la versión nueva de /odoo-chile, fué reemplazado por 'xml_sii_request1' y 'xml_sii_request2', para manejar distintas instancias de respuesta, y para comenzar a dar compatibilidad con el resto de los desarrollos de /odoo-chile, puesto que el fork que tomó @dansanti de nuestro proyecto, es del mes de Julio. En paralelo hemos ido cambiando varias cosas, lamentablemente sin poder acordar con @dansanti los cambios. Es decir hechos de una manera bastante anárquica.

@dansanti a quien yo consideraba como un buen contributor al proyecto /odoo-chile, a pesar de un excelente aporte al modificar los métodos que ejecutan la firma del documento, genera demasiados cambios en otros sectores del desarrollo, o agregados de cosas faltantes de manera bastante diferente a la línea general del proyecto, inclusive dejando de lado algunas cosas que ya estaban hechas en el proyecto /odoo-chile original.

Sin ir más lejos y a modo de ejemplo estoy queriendo dilucidar el motivo por el cual se agrega un campo forma_pago siendo que Odoo ya tiene ('payment_term'), y lo único que hacía falta era extender el 'payment_term' de Odoo para agregarle los códigos que usa el SII. Ese entre otras tantas, que están insumiendo mucho tiempo en adaptar cosas al proyecto, al tomar las contribuciones.

Hay otros casos que puedo dar, por ejemplo los nombres de variables de las referencias de documentos. En la rama 8 yo tengo desarrollados otros nombres de variable diferentes.. que a pesar de ser de otra rama, en el caso que una empresa quiera migrar, este tipo de cosas les puede dar muchos dolores de cabeza.

Aprovecho para comentar que se hace muy difícil mantener demasiadas diferencias en las ramas, y 
El tema de insistir en mantener un fork del proyecto con los issues por separado, tampoco contribuye al avance conjunto. Cada uno está en su derecho de hacer los forks que quiera, mientras se respete la autoría del código, sin embargo esto perjudica a los usuarios, que no saben qué código tomar.

**Comment by kkoci** [comment]
Hola @Danisan Ahhh, interesante, si, estoy haciendo varias pruebas, pero como dices, si se torna algo complejo probar varias versiones de varios repos.

De todas formas iré probando de las dos a ver, asi voy conociendo mejor la lógica, quien sabe, en otro momento contribuir.

Pero vaya que el sii tiene una documentación barbaramente extensa, es todo un tema no?

**Comment by Danisan** [comment]
Imagina mantener diferencias en las ramas. Todo tiempo.

**Comment by dansanti** [comment]
Ok, veré ese error, al pasar al archivo definitivo me faltó un tabulador en
esa línea, eso es lo que le falta. En unos mina mas más go el commit

**Comment by kkoci** [comment]
Si, me imagino @Danisan de todas formas, en el camino si puedo aportar algo lo aporto :), es que ésto del sii no es tan trivial jejeje

**Comment by dansanti** [comment]
@danisan ya te había comentado el por qué de medio de pago , ya que si se utiliza desde las condiciones de pago, se deberá crear una para cada tipo y combinaciones de fechas , quedando operativamente  incómodo, por eso mejor de que se cree la condición de pago, que mantiene la fecha y se combina con la forma de pago,  en el caso con tu código se tendría que crear :

30 días efectivo
30 días crédito 
(Gratuito no se donde ponerlo)
inmediato efectivo
Inmediato efectivo
(Gratuito no se donde ponerlo )
.
.
.
Eso hace de que sea complejo cuando e tiene más de un medio de pago  y distintas fechas de condiciones..
